### ISSUE TITLE
Possible memory leak with EventEmitter

### ISSUE THREAD

**Issue by jupe** [Strider-CD/strider-simple-runner#27]
Some why I get this kind of error log. Should we increase emitter MaxListeners or is this causes by some other reason ?

```
2015-02-01T20:33:13.518Z - info: [runner:simple-runner] Job started. Project: test/test Job ID: 54ce8d8375d06fe50f1819a0
2015-02-01T20:33:13.522Z - error: (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
2015-02-01T20:33:13.524Z - error: Trace
    at EventEmitter.growListenerTree (/test/strider/node_modules/eventemitter2/lib/eventemitter2.js:206:23)
    at EventEmitter.on (/test/strider/node_modules/eventemitter2/lib/eventemitter2.js:366:24)
    at Object.Job.listen (/test/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:113:13)
    at Object.Job (/test/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/job.js:57:8)
    at Object.processBuildJob [as processJob] (/test/strider/node_modules/strider-simple-runner/node_modules/strider-runner-core/lib/index.js:9:13)
    at /test/strider/node_modules/strider-simple-runner/lib/index.js:345:21
    at /test/strider/node_modules/strider-simple-runner/lib/index.js:264:7
    at /test/strider/node_modules/strider-simple-runner/node_modules/async/lib/async.js:190:13
    at /test/strider/node_modules/strider-simple-runner/node_modules/async/lib/async.js:94:25
    at /test/strider/node_modules/strider-simple-runner/node_modules/async/lib/async.js:187:17
    at /test/strider/node_modules/strider-simple-runner/node_modules/async/lib/async.js:459:34
    at /test/strider/node_modules/strider-simple-runner/lib/index.js:254:15
    at handler (/test/strider/node_modules/strider-simple-runner/lib/index.js:28:10)
    at module.exports.init (/test/strider/node_modules/strider-email-notifier/worker.js:3:12)
    at /test/strider/node_modules/strider-simple-runner/lib/index.js:257:35
    at /test/strider/node_modules/strider-simple-runner/node_modules/async/lib/async.js:454:21
2015-02-01T20:33:13.546Z - info: Git Version:1.8
```

**Comment by knownasilya** [comment]
@jupe were you able to fix the error?
